#ifndef DECOMPILED_SOURCE_HEADER_FILE
#define DECOMPILED_SOURCE_HEADER_FILE
//############################################
// THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY
//          genprog_setup.bash
//##########################################



//  Please populate with vulnerable code segments


void CHANGEME(
);

void det_CHANGEME(
#ifdef PARAMS_NEEDED
void* mycgc_calloc,
void* mycgc_malloc, 
void* mycgc_free, 
void* mycgc_realloc,
#endif
//, remaining params
);



#endif
